meta_product_name: "EMA"
meta_title: "EMA - Emergency Medical Algorithms"
meta_description: "Emergency Application that helps doctors to be more efficient when dealing with emergency situations."
meta_image: "logo_ema.png"
